name: Build and Test the Prog8 compiler

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install 64tass
        run: sudo apt-get update -y && sudo apt-get install -y 64tass

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build and test with Gradle
        run: ./gradlew build
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Create shadowJar
        run: ./gradlew shadowJar
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Create compiler shadowJar artifact
        uses: actions/upload-artifact@v3
        with:
          name: shadowJar
          path: compiler/build/libs/*-all.jar
