name: Build and Test the Prog8 compiler

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: add debian testing repository and install 64tass
        uses: myci-actions/add-deb-repo@11
        with:
          repo: http://ftp.debian.org/debian/ testing main
          repo-name: testing
          install: 64tass

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build and test with Gradle
        run: ./gradlew build shadowJar --no-daemon

      - name: Create compiler shadowJar artifact
        uses: actions/upload-artifact@v3
        with:
          name: prog8-compiler-jar-zipped
          path: compiler/build/libs/*-all.jar
