name: Build and Test the Prog8 compiler

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get missing public keys
        run: sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys 648ACFD622F3D138 0E98404D386FA1D9

      - name: add debian testing repository and install 64tass
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://ftp.debian.org/debian/ testing contrib main
          repo-name: testing
          keys-asc: https://gagis.hopto.org/repo/cppfw/pubkey.gpg
          install: 64tass

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build and test with Gradle
        run: ./gradlew build shadowJar --no-daemon

      - name: Create compiler shadowJar artifact
        uses: actions/upload-artifact@v3
        with:
          name: prog8-compiler-jar-zipped
          path: compiler/build/libs/*-all.jar
